#!/usr/bin/env bash
set -euo pipefail

ROOT="${UBUNTU100_HOME:-$HOME/ubuntu100knock}"

mkdir -p "$ROOT"/{data,logs,src,notes,tmp,backup,mock_server,experiments}

cat > "$ROOT/data/members.csv" <<'DATA'
id,name,team,score,city
1,Aki,radio,78,Urawa
2,Bob,ai,92,Hachioji
3,Chika,radio,85,Osaka
4,Daichi,core,66,Tokyo
5,Ema,ai,73,Urawa
6,Fumi,core,88,Kyoto
7,Gaku,radio,91,Saitama
8,Hana,ai,58,Tokyo
DATA

cat > "$ROOT/logs/app.log" <<'LOG'
2026-06-01 09:00:01 INFO scheduler started
2026-06-01 09:05:33 WARN gpu memory high
2026-06-01 09:06:10 ERROR failed to load config
2026-06-01 09:15:20 ERROR cuda out of memory
2026-06-02 10:03:21 WARN network unstable
2026-06-02 10:08:55 ERROR failed to save checkpoint
2026-06-02 10:12:30 INFO training finished acc=0.84
LOG

cat > "$ROOT/data/metrics.jsonl" <<'JSONL'
{"exp":"exp001","model":"rqn","acc":0.81,"loss":0.52}
{"exp":"exp002","model":"rqn","acc":0.84,"loss":0.47}
{"exp":"exp003","model":"transformer","acc":0.88,"loss":0.39}
JSONL

cat > "$ROOT/src/train.py" <<'PY'
print('training started')
print('epoch=1 loss=0.52 acc=0.81')
print('epoch=2 loss=0.47 acc=0.84')
print('training finished')
PY

cat > "$ROOT/notes/research.md" <<'MD'
# research note

This is a practice file for copy, backup, scp-like, and rsync-like exercises.
MD

cat > "$ROOT/README_LOCAL_ENV.md" <<EOF2
# Local Ubuntu 100 Knock workspace

This directory was generated by scripts/setup_local_practice_env.sh.

Recommended start:

\`\`\`bash
cd "$ROOT"
pwd
ls -lah
tail logs/app.log
grep -c "ERROR" logs/app.log
rsync -avP data/ mock_server/ubuntu100_data_rsync/
\`\`\`
EOF2

printf 'Created local practice workspace: %s\n' "$ROOT"
printf 'Next: cd %q\n' "$ROOT"
